### PR TITLE
EWB-1344 also check /web/auth for the path and update the documentation

### PR DESCRIPTION
**Pull request by ZheWangJames**
Signed-off-by: Zhe Wang <zhe.wang@zepben.com>

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [EWB-1344 Also check /ewb/auth for conf_address](https://app.clickup.com/t/6929263/EWB-1344)

**Review by kgreav — CHANGES_REQUESTED** [review]
Looks good but looks like there are some tests for this that are failing. You'll need to update the tests in test_token_fetcher.py to use the new parameters.

**Comment by ZheWangJames** [comment]
> 

Okay, will do.

**Comment by ZheWangJames** [comment]
Ok, will do.

**Comment by kgreav** [comment]
Looks good - can you add to the changelog the following Breaking change:
```create_token_fetcher now accepts a host, port, and conf_path rather than a conf_address.```

**Review by kgreav — APPROVED** [review]

**Pull request merged**
